[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "notion-client>=2.4.0",
    "openai>=1.98.0",
    "pandas>=2.3.1",
    "plotly>=6.2.0",
    "requests>=2.32.4",
    "streamlit>=1.47.1",
    "trafilatura>=2.0.0",
]
